"""
Interactive setup script for Teams webhook integration.

This script helps you configure the Teams webhook by:
1. Prompting for the webhook URL
2. Creating a .env file with the configuration
3. Testing the connection

Usage:
    python scripts/setup_teams_webhook.py
"""

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
ENV_FILE = PROJECT_ROOT / ".env"
ENV_TEMPLATE = PROJECT_ROOT / ".env.template"


def main():
    print("=" * 80)
    print("TEAMS WEBHOOK SETUP")
    print("=" * 80)
    print()

    # Check if .env already exists
    if ENV_FILE.exists():
        print(f"Found existing .env file at: {ENV_FILE}")
        overwrite = input("Do you want to overwrite it? (y/n): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled. Edit .env manually if you need to update values.")
            return
        print()

    print("STEP 1: Get Your Teams Webhook URL")
    print("-" * 80)
    print("1. Open your Microsoft Teams channel")
    print("2. Click the '...' menu next to the channel name")
    print("3. Select 'Connectors'")
    print("4. Find 'Incoming Webhook' and click 'Configure'")
    print("5. Give it a name (e.g., 'NBA Picks Bot')")
    print("6. Copy the webhook URL")
    print()

    webhook_url = input("Paste your Teams webhook URL here: ").strip()

    if not webhook_url:
        print("ERROR: Webhook URL is required")
        sys.exit(1)

    if not webhook_url.startswith("https://"):
        print("WARNING: Webhook URL should start with 'https://'")
        confirm = input("Continue anyway? (y/n): ").strip().lower()
        if confirm != 'y':
            sys.exit(1)

    print()
    print("STEP 2: Configure API URL")
    print("-" * 80)
    print("The production API URL is:")
    print("  https://nba-gbsv-api.livelycoast-b48c3cb0.eastus.azurecontainerapps.io")
    print()

    use_default = input("Use production API URL? (Y/n): ").strip().lower()

    if use_default in ['', 'y', 'yes']:
        api_url = "https://nba-gbsv-api.livelycoast-b48c3cb0.eastus.azurecontainerapps.io"
    else:
        api_url = input("Enter custom API URL: ").strip()

    print()
    print("STEP 3: Creating .env file")
    print("-" * 80)

    env_content = f"""# NBA Model Environment Variables
# Generated by setup_teams_webhook.py

# Microsoft Teams Webhook URL
TEAMS_WEBHOOK_URL={webhook_url}

# Production API URL
NBA_API_URL={api_url}

# Model version (defaults to reading from model_pack.json)
NBA_MODEL_VERSION=NBA_v33.0.21.0

# Local API port (for testing)
NBA_API_PORT=8090

# Model pack path
NBA_MODEL_PACK_PATH=models/production/model_pack.json
"""

    with open(ENV_FILE, 'w') as f:
        f.write(env_content)

    print(f"Created .env file at: {ENV_FILE}")
    print()

    print("STEP 4: Test the Connection")
    print("-" * 80)
    print("Testing requires the environment to be loaded.")
    print()

    test_now = input("Test the webhook now? (Y/n): ").strip().lower()

    if test_now in ['', 'y', 'yes']:
        print()
        print("Loading environment variables...")

        # Load .env file
        os.environ['TEAMS_WEBHOOK_URL'] = webhook_url
        os.environ['NBA_API_URL'] = api_url
        os.environ['NBA_MODEL_VERSION'] = 'NBA_v33.0.21.0'

        print("Testing Teams webhook connection...")
        print()

        # Import and run the Teams posting script
        try:
            import subprocess
            result = subprocess.run(
                [sys.executable, "scripts/post_to_teams.py", "--date", "today"],
                cwd=PROJECT_ROOT,
                capture_output=False,
                env=os.environ
            )

            if result.returncode == 0:
                print()
                print("=" * 80)
                print("SUCCESS! Teams webhook is configured and working!")
                print("=" * 80)
            else:
                print()
                print("=" * 80)
                print("Test failed. Check the error messages above.")
                print("=" * 80)

        except Exception as e:
            print(f"Error running test: {e}")
    else:
        print()
        print("Skipped test. To test manually, run:")
        print()
        print("  # Windows (PowerShell)")
        print("  Get-Content .env | ForEach-Object { if($_ -match '^([^=]+)=(.*)$') { [Environment]::SetEnvironmentVariable($matches[1], $matches[2]) } }")
        print("  python scripts/post_to_teams.py")
        print()
        print("  # Linux/Mac")
        print("  set -a; source .env; set +a")
        print("  python scripts/post_to_teams.py")

    print()
    print("=" * 80)
    print("SETUP COMPLETE")
    print("=" * 80)
    print()
    print("Next steps:")
    print("1. To post picks to Teams daily, run:")
    print("   python scripts/post_to_teams.py")
    print()
    print("2. To load environment variables in your session:")
    print()
    print("   Windows (PowerShell):")
    print("   Get-Content .env | ForEach-Object { if($_ -match '^([^=]+)=(.*)$') { [Environment]::SetEnvironmentVariable($matches[1], $matches[2]) } }")
    print()
    print("   Linux/Mac:")
    print("   set -a; source .env; set +a")
    print()
    print("3. For automated daily posting, see TEAMS_WEBHOOK_SETUP.md")
    print()


if __name__ == "__main__":
    main()
